### ISSUE TITLE
how to find these offsets

### ISSUE THREAD

**Issue by dreamc-2016** [faillacet/AssaultCubeExternal#1]

**Comment by faillacet** [comment]
The offsets were found using a combination of cheat engine, reclass, and hexrays IDA pro.  They were found by looking for specific values while viewing the games memory (trial and error).  There are quite a few tutorials online on how to find offsets if you search something along the lines of "how to find offsets in assault cube".  I would recommend using these tutorials but I will try to give a rough rundown of the process I used.  

Most of the important variables needed for this project are found in the "Player Entity" class so the first thing you need to do is find a pointer to the player entity.  I did this by simply loading up a single player lobby and using cheat engine's memory scan function to find the memory location of the local player's health.  By damaging myself and scanning for the new values its relatively quick to find the health variable.  From there you want to explore the surrounding memory region to find the base address of the class.  Then you want to use cheat engine's pointer scanning feature to find a static pointer that points to the class's base address.  This is a pointer that is going to be the same on each boot-up of the game.  From there it is mostly playing around with the values in the same memory region and figuring out what they do/what values they hold and recording the offsets for use within the program.  For clarity, the offsets in this context are the relative distance from whatever address they are being compared to.  For example, the health offset is the distance from the base address of the Entity class, while the offsets I have like playerent are relative to the base address of the assault cube client.

**Comment by dreamc-2016** [comment]
Your reply has helped me a lot. Thank you
